### ISSUE TITLE
Positive test toggle showing more positive tests than total tests

### ISSUE THREAD

**Issue by housseindjirdeh** [lachlanjc/covidtesting#1]
Hi @lachlanjc!

This is so great, thanks for taking the time to build this.

Just wanted to flag something that might be a bug. Switching to the `positive` toggle for Top States shows more positive tests than total tests:

<img width="1183" alt="Screen Shot 2020-03-25 at 10 56 22 AM" src="https://user-images.githubusercontent.com/12476932/77569780-20f5ef80-6ea1-11ea-8fb3-790fb4884a9c.png">

I'm assuming the numbers just get swapped when they shouldn't :)

**Comment by lachlanjc** [comment]
Thanks! Yeah, it’s a bug, the numbers get flipped, you’re totally right. I’m working on fixing it, just busy with a bunch of things. You/anyone else is very welcome to make PRs in the meantime :)

**Comment by ginoemiliozzi** [comment]
Hey I just made a PR to fix this https://github.com/lachlanjc/covidtesting/pull/2
You can review and merge it if you're happy with it :)

**Comment by lachlanjc** [comment]
Thanks so much for this @ginoemiliozzi <3 let me know if you spot anything else @housseindjirdeh!
