### ISSUE TITLE
Louisiana Missing Label

### ISSUE THREAD

**Issue by schwartzadev** [lachlanjc/covidtesting#3]
Hey! I just noticed that Louisiana seems to be missing its state label:
![image](https://user-images.githubusercontent.com/18607205/77672041-062d8480-6f4e-11ea-8b90-c2cf4bf40b95.png)

Great visualizations 👍

**Comment by galvinma** [comment]
This is due to a spelling error in the states.json file. 

Lousiana --> Louisiana

Resolved by #4

**Comment by lachlanjc** [comment]
Yep, super appreciate @galvinma’s PR fixing this. Should be good to go now. Thanks!
